shell="/bin/ash"
live_config_reload=false
ipc_socket=false
[scrolling]
history=65536
multiplier=0
[window]
opacity=0.95
[font]
size=7
[font.normal]
family="Monaco"
[colors]
draw_bold_text_with_bright_colors=true
[colors.bright]
black="0x606060"
red="0xff1717"
green="0x00c000"
yellow="0x999920"
blue="0x5000ff"
magenta="0xf040a0"
cyan="0x00a0d0"
white="0xffffff"
[colors.normal]
black="0x000000"
red="0xa00000"
green="0x009000"
yellow="0xff6000"
blue="0x0050a0"
magenta="0x901050"
cyan="0x007080"
white="0xffffff"
[colors.dim]
black="0x000000"
red="0x600000"
green="0x004000"
yellow="0x806000"
blue="0x003060"
magenta="0x600030"
cyan="0x003747"
white="0xffffff"
[colors.primary]
background="0xffffff"
foreground="0x000000"
