music_directory "~/mus"
playlist_directory "~/.config/mpd/playlists"
#pid_file "/run/user/6969/mpd/pid" # ignored in systemd mode
bind_to_address "/run/user/6969/mpd/socket"
db_file "~/.cache/mpd.db"
#state_file "~/.local/state/mpd.state"
log_file "syslog"
log_level "error"
restore_paused "yes"
replaygain "track"
replaygain_preamp "0"
replaygain_missing_preamp "0"
volume_normalization "no"
#audio_output {
#        type "pulse"
#        name "PulseAudio output"
#}
audio_output {
    type "pipewire"
    name "PipeWire Sound Server"
    format "44100:16:1"
}
#audio_output {
#    type  "fifo"
#    name  "mpdfifo"
#    path  "/run/user/6969/mpd/mpd.fifo"
#    enabled  "yes"
#    format  "44100:16:2"
#}
