{ bg0         : Text
, bg1         : Text
, bg2         : Text
, bg3         : Text
, bg4         : Text
, bg5         : Text
, fg0         : Text
, fg1         : Text
, cyan        : Text
, orange      : Text
, orange_dim  : Text
, amber       : Text
, yellow      : Text
, green       : Text
, green_light : Text
, red         : Text
, red_soft    : Text
, blue        : Text
, blue_light  : Text
, white       : Text
}
