[general]
default-save-path=~/dl
log-file=~/.local/state/logs/aerc.log
default-menu-cmd=fzy
[ui]
mouse-enabled=true
styleset-name=wodk
empty-message=bad crop
empty-dirlist=bad crop
empty-subject=bad crop
new-message-bell=false
icon-unencrypted=!
icon-encrypted=$
icon-signed=$
icon-signed-encrypted=$
icon-unknown=?
icon-invalid=!
[statusline]
column-separator=""
separator="|"
[viewer]
pager=less -Rc
[compose]
#editor=vi -c set tabstop=2
editor=vim
[filters]
text/plain=wrap -w 99|colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
#text/html=html|colorize
text/html=! w3m -I UTF-8 -T text/html
[openers]
x-scheme-handler/http*=printf '%s' {} | wl-copy
