profile=fast
#ao=pipewire,alsa,pulseaudio
video-sync=display-resample
#vo=gpu-next
gpu-api=vulkan
#gpu-context=waylandvk
gpu-context=x11vk
hwdec=vaapi
script-opts=ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"
ytdl-raw-options=format="(((bv*[fps<=30]/bv*)[height<=720])[ext=mp4]/(wv*[fps<=30]/wv*)) + (((ba[ext=m4a])[fps<=30])[height<=720] / ba)"
sub-ass-force-style=Outline=4
volume-max=250.0
screenshot-format=png
demuxer-lavf-o=extension_picky=0
