# Ayu Dark palette
{
  accent = "#FF8F40",
  bg = "#1F2430",
  selection = "#3E4B59",
  branch = "#95E6CB",
  git_status = "#AAD94C",

  background = "#0F1419",
  foreground = "#E6E1CF",

  normal = {
    black = "#000000",
    red = "#FF3333",
    green = "#B8CC52",
    yellow = "#E7C547",
    blue = "#36A3D9",
    magenta = "#F07178",
    cyan = "#95E6CB",
    white = "#FFFFFF",
  },

  bright = {
    black = "#5C6773",
    red = "#FF3333",
    green = "#BBE67E",
    yellow = "#E7C547",
    blue = "#5CCFE6",
    magenta = "#F07178",
    cyan = "#95E6CB",
    white = "#FFFFFF",
  },

  dim = {
    black = "#0F1419",
    red = "#A00000",
    green = "#009000",
    yellow = "#806000",
    blue = "#0050A0",
    magenta = "#901050",
    cyan = "#007080",
    white = "#FFFFFF",
  },
}
