font_size 9.0
cursor #ff4faf
cursor_text_color #ffffff
scrollback_lines 131071
scrollback_indicator_opacity 0.0
detect_urls no
repaint_delay 20
input_delay 6
sync_to_monitor no
enable_audio_bell no
remember_window_size no
confirm_os_window_close 0
background #ffffff
foreground #000000
color0 #000000
color1 #a00000
color2 #009000
color3 #aa5000
color4 #0050a0
color5 #901050
color6 #007080
color7 #ffffff
color8 #400020
color9 #ff1717
color10 #00c000
color11 #ee6000
color12 #5000ff
color13 #f040a0
color14 #00a0d0
color15 #ffffff
shell /usr/bin/yash
editor /usr/bin/nvim
allow_hyperlinks no
#shell_integration no
map opt+page_up scroll_page_up
map opt+page_down scroll_page_down


# BEGIN_KITTY_FONTS
font_family      family=Monaco postscript_name=Monaco
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
text_composition_strategy 2.0
