set-option -g default-terminal screen-256color
set-option -g mode-keys vi
set-option -g status-keys vi
set-option -g pane-active-border-style fg=magenta
set-option -g pane-border-style fg=black
setw -g monitor-activity on
set -g default-shell ~/.local/bin/pwsh -nol
set -g visual-activity on
set -g status off
set -g mouse on
