#font=Monaco:size=8,HanaMinB:size=8
#font=monospace:size=9
font=CozetteVector:size=13
#shell=/var/home/linuxbrew/.linuxbrew/bin/yash
shell=nu
#shell=nu
#shell=pwsh -NoLogo
bold-text-in-bright=palette-based
resize-by-cells=no
[scrollback]
lines=131071
indicator-position=none
[colors]
background=ffffff
foreground=000000
regular0=000000
regular1=a00000
regular2=009000
regular3=aa5000
regular4=0050a0
regular5=901050
regular6=007080
regular7=ffffff
bright0=400020
bright1=ff1717
bright2=00c000
bright3=ee6000
bright4=5000ff
bright5=f040a0
bright6=00a0d0
bright7=ffffff
dim0=000000
dim1=600000
dim2=004000
dim3=804000
dim4=003060
dim5=600030
dim6=003747
dim7=b000d0
[csd]
color=ff101010
button-color=ffffffff
hide-when-maximized=yes
